# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chenweidong/Documents/zhuifan/zhuifanmain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_zhuifan(object):
    def setupUi(self, zhuifan):
        zhuifan.setObjectName(_fromUtf8("zhuifan"))
        zhuifan.resize(681, 593)
        self.weekindex = QtGui.QTextBrowser(zhuifan)
        self.weekindex.setGeometry(QtCore.QRect(10, 90, 651, 201))
        self.weekindex.setObjectName(_fromUtf8("weekindex"))
        self.sun = QtGui.QPushButton(zhuifan)
        self.sun.setGeometry(QtCore.QRect(10, 60, 51, 27))
        self.sun.setObjectName(_fromUtf8("sun"))
        self.mon = QtGui.QPushButton(zhuifan)
        self.mon.setGeometry(QtCore.QRect(80, 60, 51, 27))
        self.mon.setObjectName(_fromUtf8("mon"))
        self.tue = QtGui.QPushButton(zhuifan)
        self.tue.setGeometry(QtCore.QRect(150, 60, 51, 27))
        self.tue.setObjectName(_fromUtf8("tue"))
        self.wed = QtGui.QPushButton(zhuifan)
        self.wed.setGeometry(QtCore.QRect(220, 60, 51, 27))
        self.wed.setObjectName(_fromUtf8("wed"))
        self.thu = QtGui.QPushButton(zhuifan)
        self.thu.setGeometry(QtCore.QRect(290, 60, 51, 27))
        self.thu.setObjectName(_fromUtf8("thu"))
        self.fri = QtGui.QPushButton(zhuifan)
        self.fri.setGeometry(QtCore.QRect(360, 60, 51, 27))
        self.fri.setObjectName(_fromUtf8("fri"))
        self.sat = QtGui.QPushButton(zhuifan)
        self.sat.setGeometry(QtCore.QRect(430, 60, 51, 27))
        self.sat.setObjectName(_fromUtf8("sat"))
        self.saveindex = QtGui.QTextBrowser(zhuifan)
        self.saveindex.setGeometry(QtCore.QRect(10, 350, 651, 192))
        self.saveindex.setObjectName(_fromUtf8("saveindex"))
        self.label = QtGui.QLabel(zhuifan)
        self.label.setGeometry(QtCore.QRect(20, 320, 81, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.searchtext = QtGui.QLineEdit(zhuifan)
        self.searchtext.setGeometry(QtCore.QRect(240, 10, 221, 27))
        self.searchtext.setObjectName(_fromUtf8("searchtext"))
        self.searchbtn = QtGui.QPushButton(zhuifan)
        self.searchbtn.setGeometry(QtCore.QRect(470, 10, 98, 27))
        self.searchbtn.setObjectName(_fromUtf8("searchbtn"))
        self.index01 = QtGui.QPushButton(zhuifan)
        self.index01.setGeometry(QtCore.QRect(20, 100, 191, 27))
        self.index01.setText(_fromUtf8(""))
        self.index01.setObjectName(_fromUtf8("index01"))
        self.index02 = QtGui.QPushButton(zhuifan)
        self.index02.setGeometry(QtCore.QRect(240, 100, 191, 27))
        self.index02.setText(_fromUtf8(""))
        self.index02.setObjectName(_fromUtf8("index02"))
        self.index03 = QtGui.QPushButton(zhuifan)
        self.index03.setGeometry(QtCore.QRect(460, 100, 191, 27))
        self.index03.setText(_fromUtf8(""))
        self.index03.setObjectName(_fromUtf8("index03"))
        self.index04 = QtGui.QPushButton(zhuifan)
        self.index04.setGeometry(QtCore.QRect(20, 130, 191, 27))
        self.index04.setText(_fromUtf8(""))
        self.index04.setObjectName(_fromUtf8("index04"))
        self.index05 = QtGui.QPushButton(zhuifan)
        self.index05.setGeometry(QtCore.QRect(240, 130, 191, 27))
        self.index05.setText(_fromUtf8(""))
        self.index05.setObjectName(_fromUtf8("index05"))
        self.index06 = QtGui.QPushButton(zhuifan)
        self.index06.setGeometry(QtCore.QRect(460, 130, 191, 27))
        self.index06.setText(_fromUtf8(""))
        self.index06.setObjectName(_fromUtf8("index06"))
        self.index07 = QtGui.QPushButton(zhuifan)
        self.index07.setGeometry(QtCore.QRect(20, 160, 191, 27))
        self.index07.setText(_fromUtf8(""))
        self.index07.setObjectName(_fromUtf8("index07"))
        self.index10 = QtGui.QPushButton(zhuifan)
        self.index10.setGeometry(QtCore.QRect(20, 190, 191, 27))
        self.index10.setText(_fromUtf8(""))
        self.index10.setObjectName(_fromUtf8("index10"))
        self.index13 = QtGui.QPushButton(zhuifan)
        self.index13.setGeometry(QtCore.QRect(20, 220, 191, 27))
        self.index13.setText(_fromUtf8(""))
        self.index13.setObjectName(_fromUtf8("index13"))
        self.index16 = QtGui.QPushButton(zhuifan)
        self.index16.setGeometry(QtCore.QRect(20, 250, 191, 27))
        self.index16.setText(_fromUtf8(""))
        self.index16.setObjectName(_fromUtf8("index16"))
        self.index08 = QtGui.QPushButton(zhuifan)
        self.index08.setGeometry(QtCore.QRect(240, 160, 191, 27))
        self.index08.setText(_fromUtf8(""))
        self.index08.setObjectName(_fromUtf8("index08"))
        self.index11 = QtGui.QPushButton(zhuifan)
        self.index11.setGeometry(QtCore.QRect(240, 190, 191, 27))
        self.index11.setText(_fromUtf8(""))
        self.index11.setObjectName(_fromUtf8("index11"))
        self.index14 = QtGui.QPushButton(zhuifan)
        self.index14.setGeometry(QtCore.QRect(240, 220, 191, 27))
        self.index14.setText(_fromUtf8(""))
        self.index14.setObjectName(_fromUtf8("index14"))
        self.index17 = QtGui.QPushButton(zhuifan)
        self.index17.setGeometry(QtCore.QRect(240, 250, 191, 27))
        self.index17.setText(_fromUtf8(""))
        self.index17.setObjectName(_fromUtf8("index17"))
        self.index09 = QtGui.QPushButton(zhuifan)
        self.index09.setGeometry(QtCore.QRect(460, 160, 191, 27))
        self.index09.setText(_fromUtf8(""))
        self.index09.setObjectName(_fromUtf8("index09"))
        self.index12 = QtGui.QPushButton(zhuifan)
        self.index12.setGeometry(QtCore.QRect(460, 190, 191, 27))
        self.index12.setText(_fromUtf8(""))
        self.index12.setObjectName(_fromUtf8("index12"))
        self.index15 = QtGui.QPushButton(zhuifan)
        self.index15.setGeometry(QtCore.QRect(460, 220, 191, 27))
        self.index15.setText(_fromUtf8(""))
        self.index15.setObjectName(_fromUtf8("index15"))
        self.index18 = QtGui.QPushButton(zhuifan)
        self.index18.setGeometry(QtCore.QRect(460, 250, 191, 27))
        self.index18.setText(_fromUtf8(""))
        self.index18.setObjectName(_fromUtf8("index18"))
        self.first = QtGui.QComboBox(zhuifan)
        self.first.setGeometry(QtCore.QRect(60, 10, 78, 27))
        self.first.setObjectName(_fromUtf8("first"))
        self.first.addItem(_fromUtf8(""))
        self.first.addItem(_fromUtf8(""))
        self.save01 = QtGui.QPushButton(zhuifan)
        self.save01.setGeometry(QtCore.QRect(20, 370, 191, 27))
        self.save01.setText(_fromUtf8(""))
        self.save01.setObjectName(_fromUtf8("save01"))
        self.save02 = QtGui.QPushButton(zhuifan)
        self.save02.setGeometry(QtCore.QRect(240, 370, 191, 27))
        self.save02.setText(_fromUtf8(""))
        self.save02.setObjectName(_fromUtf8("save02"))
        self.save03 = QtGui.QPushButton(zhuifan)
        self.save03.setGeometry(QtCore.QRect(460, 370, 191, 27))
        self.save03.setText(_fromUtf8(""))
        self.save03.setObjectName(_fromUtf8("save03"))
        self.save05 = QtGui.QPushButton(zhuifan)
        self.save05.setGeometry(QtCore.QRect(240, 410, 191, 27))
        self.save05.setText(_fromUtf8(""))
        self.save05.setObjectName(_fromUtf8("save05"))
        self.save06 = QtGui.QPushButton(zhuifan)
        self.save06.setGeometry(QtCore.QRect(460, 410, 191, 27))
        self.save06.setText(_fromUtf8(""))
        self.save06.setObjectName(_fromUtf8("save06"))
        self.save04 = QtGui.QPushButton(zhuifan)
        self.save04.setGeometry(QtCore.QRect(20, 410, 191, 27))
        self.save04.setText(_fromUtf8(""))
        self.save04.setObjectName(_fromUtf8("save04"))
        self.save08 = QtGui.QPushButton(zhuifan)
        self.save08.setGeometry(QtCore.QRect(240, 450, 191, 27))
        self.save08.setText(_fromUtf8(""))
        self.save08.setObjectName(_fromUtf8("save08"))
        self.save09 = QtGui.QPushButton(zhuifan)
        self.save09.setGeometry(QtCore.QRect(460, 450, 191, 27))
        self.save09.setText(_fromUtf8(""))
        self.save09.setObjectName(_fromUtf8("save09"))
        self.save07 = QtGui.QPushButton(zhuifan)
        self.save07.setGeometry(QtCore.QRect(20, 450, 191, 27))
        self.save07.setText(_fromUtf8(""))
        self.save07.setObjectName(_fromUtf8("save07"))
        self.save11 = QtGui.QPushButton(zhuifan)
        self.save11.setGeometry(QtCore.QRect(240, 490, 191, 27))
        self.save11.setText(_fromUtf8(""))
        self.save11.setObjectName(_fromUtf8("save11"))
        self.save12 = QtGui.QPushButton(zhuifan)
        self.save12.setGeometry(QtCore.QRect(460, 490, 191, 27))
        self.save12.setText(_fromUtf8(""))
        self.save12.setObjectName(_fromUtf8("save12"))
        self.save10 = QtGui.QPushButton(zhuifan)
        self.save10.setGeometry(QtCore.QRect(20, 490, 191, 27))
        self.save10.setText(_fromUtf8(""))
        self.save10.setObjectName(_fromUtf8("save10"))

        self.retranslateUi(zhuifan)
        QtCore.QMetaObject.connectSlotsByName(zhuifan)

    def retranslateUi(self, zhuifan):
        zhuifan.setWindowTitle(_translate("zhuifan", "追番", None))
        self.sun.setText(_translate("zhuifan", "星期日", None))
        self.mon.setText(_translate("zhuifan", "星期一", None))
        self.tue.setText(_translate("zhuifan", "星期二", None))
        self.wed.setText(_translate("zhuifan", "星期三", None))
        self.thu.setText(_translate("zhuifan", "星期四", None))
        self.fri.setText(_translate("zhuifan", "星期五", None))
        self.sat.setText(_translate("zhuifan", "星期六", None))
        self.label.setText(_translate("zhuifan", "已收藏：", None))
        self.searchbtn.setText(_translate("zhuifan", "查找", None))
        self.first.setItemText(0, _translate("zhuifan", "Bilibili", None))
        self.first.setItemText(1, _translate("zhuifan", "Soku", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    zhuifan = QtGui.QDialog()
    ui = Ui_zhuifan()
    ui.setupUi(zhuifan)
    zhuifan.show()
    sys.exit(app.exec_())

